version: "{build}"

platform: x64

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.5.1

install:
  - appveyor DownloadFile https://atom.io/download/windows?channel=beta -FileName AtomSetup.exe
  - AtomSetup.exe /silent
  - set PATH=%LOCALAPPDATA%\atom\bin;%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - go get -u github.com/nsf/gocode
  - mkdir c:\gopath

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - SET PATH=%LOCALAPPDATA%\atom\bin;%GOPATH%\bin;%PATH%
  - apm clean
  - apm install
  - apm install environment
  - apm install go-config
  - atom --test spec

test: off
deploy: off
